services:

  postgres:
    image: postgres:16
    container_name: workflow-postgres
    restart: always

    environment:
      POSTGRES_DB: workflowdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: workflow-zookeeper
    restart: unless-stopped

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: workflow-kafka
    restart: unless-stopped

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ml-service:
    build: ./ml-service
    container_name: workflow-ml

    ports:
      - "8000:8000"

  backend:
    build: ./workflow
    container_name: workflow-backend

    depends_on:
      - postgres
      - kafka
      - ml-service

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"

  frontend:
    build: ./workflow-ui
    container_name: workflow-ui

    depends_on:
      - backend

    ports:
      - "5173:80"

volumes:
  postgres-data: