spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/workflowdb
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: workflow-group
      auto-offset-reset: earliest

app:
  kafka:
    enabled: true

ml:
  service:
    url: http://ml-service:8000